### ISSUE TITLE
reIntroduceTrapdoorUpdateSkipping no longer works in version 1.20.4

### ISSUE THREAD

**Issue by CommanderT3706** [fxmorin/carpet-fixes#168]
**Describe the bug**
The rule reIntroduceTrapdoorUpdateSkipping does not work in version 1.20.4 of Minecraft. This is due to the trapdoor not being able to reach the state of suppression, due to redstone dust being broken instantly when placed on the trapdoor.

**To Reproduce**
1. Enable reIntroduceTrapdoorUpdateSkipping
2. Attempt to build update skipper
3. Redstone is unable to be placed

**Expected behavior**
The redstone dust remains on the trapdoor, priming the skipper.

**Minecraft Version:**
 - v1.20.4
**Carpet-Fixes Version:**
 - v1.17.0
**Carpet Version:**
 - v1.4.128

**Additional context**
The test was conducted on both a single player and multiplayer world.

**Comment by CommanderT3706** [comment]
This seems to be due to the fact that blocks that require support now fall off trapdoors once opened. I'm unsure of how this can be fixed though.

**Comment by Crystal0404** [comment]
It has been fixed by https://github.com/FxMorin/carpet-fixes/pull/171

**Comment by SirKaayser** [comment]
> It has been fixed by #171

Hello, you say it's fixed, but it still doesn't work for me, what should I do to make it work? I've seen that it's added in the code but it's not in the downloadable .jar file. Thanks for the help in advance.

**Comment by Crystal0404** [comment]
> > It has been fixed by #171
> 
> Hello, you say it's fixed, but it still doesn't work for me, what should I do to make it work? I've seen that it's added in the code but it's not in the downloadable .jar file. Thanks for the help in advance.

You can use the `dustTrapdoorReintroduced` rule from `tis-carpet`

https://carpet.tis.world/docs/rules#dusttrapdoorreintroduced

https://carpet.tis.world/docs/rules#instantblockupdaterreintroduced

https://modrinth.com/mod/carpet-tis-addition
